### ISSUE TITLE
CCL version?

### ISSUE THREAD

**Issue by dkirkby** [LSSTDESC/N5K#18]
Using the main branch of N5K and the latest CCL from conda-forge, `example_benchmark.py` fails with:
```
Traceback (most recent call last):
  File "example_benchmark.py", line 18, in <module>
    cal_lm.setup()
  File "/Users/david/Cosmo/DESC/N5K/N5K/n5k/calculator_ccl.py", line 14, in setup
    self.cosmo = ccl.CosmologyCalculator(Omega_c=par['Omega_m']-par['Omega_b'],
AttributeError: module 'pyccl' has no attribute 'CosmologyCalculator'
```
I guess I need to install CCL from source to pickup the new CCL calculator mode?  I don't see instructions  for that [here](https://ccl.readthedocs.io/en/latest/source/installation.html) but should `python setup.py install` work?

**Comment by c-d-leonard** [comment]
Hi @dkirkby ah yes, right - you will need to get the latest version of master from the github. If you then do `pip install -e .` in the home directory, that should work to install. Let me know if you have any more issues with this.

**Comment by dkirkby** [comment]
Thanks @c-d-leonard, that works (after installing CMake).
