### ISSUE TITLE
Clarification on kernels and bias

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/N5K#7]
Just to confirm, the bias is NOT included in the kernels right? I was naively expecting it was, and that the problem was literally to solve the integral from the README:
![image](https://user-images.githubusercontent.com/861591/101290597-a2a96580-3803-11eb-8c92-dca038a553a5.png)
but from a quick test, looks like I need to include the bias for the clustering probe if I want to match CCL. 
Can the organizers confirm?

Because I cheated and looked at what @tilmantroester was up to, it looks like he made the same assumption and is not loading the bias.

**Comment by damonge** [comment]
Oh, damn. Yes, you're right. Not sure why I didn't see that.

Humm, ok, I think it may be best for us to reload the kernels incorporating the bias so everything is consistent. Let me get back to you.

**Comment by damonge** [comment]
This was fixed (bias now provided with the kernels)
